blog/apps/main_app/urls.py
from django.urls import path

from . import views

app_name = 'main_app'
urlpatterns = [
    path('', views.index, name = 'index'),

    path('profile/', views.profile, name = 'profile'),
    path('profile/edit', views.edit_profile, name = 'edit_profile'),

    path('login/', views.login, name = 'login'),
    path('logout/', views.logoutUser, name = 'logoutUser'),
    path('register/', views.register, name = 'register'),

    path('category/', views.category, name = 'category'),
    path('article/', views.article, name = 'article'),
    path('loadArticles/', views.loadArticles, name = 'loadArticles'),

    path('article/<int:article_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
    path('loadComments/', views.loadComments, name = 'loadComments'),
    path('deleteComment/', views.deleteComment, name = 'deleteComment')
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main_app.urls')),
    path(r'supers3cret4dm1n/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/main_app/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.conf import settings

from django.contrib.auth.models import User

from PIL import Image

import os
from django.db.models.signals import pre_save
from django.dispatch.dispatcher import receiver

class UserProfile(models.Model):

    user   = models.OneToOneField(User, on_delete=models.CASCADE)
    bio    = models.CharField('Описание пользователя', max_length=170)
    avatar = models.ImageField(upload_to='img/users', max_length=100, default='img/default_images/defaultUser.png')

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save()

        img  = Image.open(self.avatar.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)  
            img.save(self.avatar.path)

class Category(models.Model):
    category_no   = models.IntegerField('Номер категории', primary_key=True)
    name          = models.CharField('Название категории', max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class Article(models.Model):
    article_image       = models.ImageField(upload_to='img/articles', max_length=100, default='img/default_images/default.jpg')
    article_title       = models.CharField('Название статьи', max_length = 30)
    article_description = models.CharField('Краткое описание статьи', max_length = 150)
    article_text        = models.TextField('Текст статьи')
    pub_date            = models.DateTimeField('Дата публикации')
    is_main_in_category = models.BooleanField('Главная статья в своей категории(можно поставить только 1)', default=False)
    is_main_in_homepage = models.BooleanField('Главная статья на домашней страницу(всего 3)', default=False)
    author              = models.ForeignKey(UserProfile, on_delete = models.CASCADE)
    category            = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, db_column='category_no', default=14)
    likes               = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.is_main_in_category:
            try:
                temp = Article.objects.get(is_main_in_category=True, category=self.category)
                if self != temp:
                    temp.is_main_in_category = False
                    temp.save()
            except Article.DoesNotExist:
                pass

        if self.is_main_in_homepage:
            try:
                main_count = len(Article.objects.filter(is_main_in_homepage=True))
                if main_count >= 3:
                    self.is_main_in_homepage = False
            except Article.DoesNotExist:
                pass
            
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

    # For russian lang
    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

class Comment(models.Model):
    article      = models.ForeignKey(Article, on_delete = models.CASCADE)
    
    author       = models.ForeignKey(UserProfile, on_delete = models.CASCADE)
    comment_text = models.CharField('Текст комментария', max_length = 200)
    pub_date     = models.DateTimeField('Дата публикации')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

# Delete images from media folder when they uploaded
@receiver(pre_save, sender=UserProfile)
def delete_avatar(sender, instance, *args, **kwargs):
    try:
        old_instance = UserProfile.objects.get(id=instance.id)
        old_avatar = os.path.basename(old_instance.avatar.name)
        new_avatar = os.path.basename(instance.avatar.name)

        if (old_avatar != new_avatar):
            if (old_avatar != 'defaultUser.png'):
                os.remove(old_instance.avatar.path)
            
    except UserProfile.DoesNotExist:
        return None

@receiver(pre_save, sender=Article)
def delete_img(sender, instance, *args, **kwargs):
    try:
        old_instance = Article.objects.get(id=instance.id)
        old_image = os.path.basename(old_instance.article_image.name)
        new_image = os.path.basename(instance.article_image.name)

        if (new_image != old_image):
            if (old_image != 'default.jpg'):
                os.remove(old_instance.article_image.path)
            
    except Article.DoesNotExist:
        return None

blog/apps/main_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from main_app.models import UserProfile

class CreateUserForm(UserCreationForm):
    username = forms.CharField(error_messages={'required': 'Введите имя пользователя'})
    
    error_messages = {
        'password_mismatch': ("Пароли не совпадают"),
    }

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'username-edit'})
        }

class ProfileUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)

        self.fields['bio'].required = False

    class Meta:
        model = UserProfile
        fields = ['bio', 'avatar']
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'bio-edit', 'maxlength': '170', 'placeholder': 'Введите короткое описание'})
        }

blog/apps/main_app/views.py
# TODO: Make like button
# TODO: Customizate admin panel
# TODO: Make ability to create, update and delete articles

import json

from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404

from django.utils import timezone

from .models import Category, Article, Comment, UserProfile

from .forms import CreateUserForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib import messages

from django.contrib.auth.decorators import login_required

from django import forms

def index(req):

    categories          = Category.objects.all()
    main_articles       = Article.objects.filter(is_main_in_homepage=True).order_by('likes') # Get three main articles and order by likes
    main_articles_array = main_articles[1:]

    popular_articles = Article.objects.order_by('-likes')[:10]

    context = {
        'categories': categories,
        'main_article': main_articles[0],
        'articles': popular_articles, 
        'main_articles': main_articles_array
    }

    if req.user.is_authenticated:
        profile = UserProfile.objects.get(user = req.user)
        context['profile'] = profile

    return render(req, 'pages/index.html', context)

def category(req):

    categories   = Category.objects.all()
    id           = req.GET.get('id')
    current_cat  = Category.objects.get(category_no = id)
    articles     = Article.objects.filter(category_id = id).order_by('-likes')[:9]
    
    try:
        main_article = Article.objects.get(category_id = id, is_main_in_category = True)    
    except Article.DoesNotExist:
        main_article = None
    
    context = {
        'categories': categories, 
        'articles': articles, 
        'main_article': main_article, 
        'current_cat': current_cat, 
        'category_id': int(id)
    }

    if req.user.is_authenticated:
        profile = UserProfile.objects.get(user = req.user)
        context['profile'] = profile

    return render(req, 'pages/category.html', context)

def loadArticles(req):
    count = req.GET.get('count', 10)
    id    = req.GET.get('id')
    count = int(count)

    if id is not None:
        id = int(id)
        popular_articles = Article.objects.filter(is_main_in_category=False, category_id = id).order_by('-likes')[count:count+9]
    else:
        popular_articles = Article.objects.filter(is_main_in_homepage=False).order_by('-likes')[count:count+10]

    response_data = []

    for a in popular_articles:
        article                = {}
        article["id"]          = a.id
        article["img"]         = a.article_image.url
        article["title"]       = a.article_title
        article["desc"]        = a.article_description
        article["author_name"] = a.author.user.username
        article["author_id"]   = a.author.id
        article["date"]        = a.pub_date.strftime("%d %B %Y %H:%M")
        article["category"]    = a.category.name
        article["category_no"] = a.category.category_no
        article["likes"]       = a.likes

        response_data.append(article)

    context = json.dumps(response_data)

    return HttpResponse(context, content_type="application/json")

def article(req):

    id         = req.GET.get('id')
    categories = Category.objects.all()
   
    try:
        article        = Article.objects.get(id = id)
        profile        = UserProfile.objects.get(id = article.author.id)
    except:
        raise Http404('Статья не найдена')

    latest_comments_list = article.comment_set.order_by('-id')[:10]
    comment_count        = article.comment_set.count()
    
    article.article_text = parseArticleText(article.article_text)

    context = {
        'article': article, 
        'categories': categories, 
        'category_id': article.category_id, 
        'comments': latest_comments_list, 
        'author_profile': profile,
        'comment_count': comment_count
    }

    if req.user.is_authenticated:
        currentProfile = UserProfile.objects.get(user = req.user)
        context['profile'] = currentProfile

    return render(req, 'pages/article.html', context)


def profile(req):

    id      = req.GET.get('id')
    profile = UserProfile.objects.get(user = req.user)

    try:
        user_profile = UserProfile.objects.get(id = id)
    except:
        raise Http404('Пользователь не найден')

    last_articles = Article.objects.filter(author = user_profile).order_by('-pub_date')
    last_comments = Comment.objects.filter(author = user_profile).order_by('-pub_date')

    if (last_articles):
        last_articles = last_articles[0:8]

    if (last_comments):
        last_comments = last_comments[0:4]

    return render(req, 'user/profile.html', {'lastArticles': last_articles, 'lastComments': last_comments, 'profile': profile, 'load_profile': user_profile})

@login_required
def edit_profile(req):

    profile = UserProfile.objects.get(user = req.user)

    if req.method == 'POST':

        u_form = UserUpdateForm(req.POST, instance = req.user)
        p_form = ProfileUpdateForm(req.POST, req.FILES, instance = profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(req, 'Ваш аккаунт обновлен')
            return redirect('/profile/edit')

    else:
        u_form = UserUpdateForm(instance = req.user)
        p_form = ProfileUpdateForm(instance = profile)

    context = {'u_form': u_form, 'p_form': p_form, 'profile': profile}

    return render(req, 'user/edit.html', context)


def leave_comment(req, article_id):

    if req.user.is_authenticated:

        try:
            a = Article.objects.get(id = article_id)
        except:
            raise Http404("Статья не найдена")

        data = json.loads(req.body)
        profile = UserProfile.objects.get(user = req.user)
        
        c = a.comment_set.create(author = profile, comment_text = data['text'], pub_date = timezone.now())

        comment                = {}
        comment["id"]          = c.id
        comment["image"]       = c.author.avatar.url
        comment["author_name"] = c.author.user.username
        comment["author_id"]   = c.author.user.id
        comment["show-delete"] = True
        comment["pub_date"]    = c.pub_date.strftime("%d %B %Y %H:%M")
        comment["text"]        = c.comment_text

        context = json.dumps(comment)

        return HttpResponse(context, content_type="application/json")

    else:
        jsonr = json.dumps({ 'authenticated': False })
        return HttpResponse(jsonr, content_type="application/json")

def loadComments(req):

    count = req.GET.get('count', 10)
    count = int(count)

    latest_comments = Comment.objects.order_by('-id')[count:count+10]

    response_data = []

    for c in latest_comments:
        comment                = {}
        comment["id"]          = c.id
        comment["image"]       = c.author.avatar.url
        comment["author_name"] = c.author.user.username
        comment["author_id"]   = c.author.user.id
        comment["pub_date"]    = c.pub_date.strftime("%d %B %Y %H:%M")
        comment["text"]        = c.comment_text

        if c.author.user == req.user:
            comment["show-delete"] = True
        else:
            comment["show-delete"] = False

        response_data.append(comment)

    context = json.dumps(response_data)

    return HttpResponse(context, content_type="application/json")

def deleteComment(req):

    id = req.GET.get('id')

    Comment.objects.filter(id = id).delete()

    jsonr = json.dumps({ 'deleted': True })
    return HttpResponse(jsonr, content_type="application/json")


def login(req):

    if req.user.is_authenticated:
        return redirect('/')
    else:
        context = {}

        if req.method == 'POST':
            username = req.POST["username"]
            password = req.POST["password"]

            user = authenticate(req, username=username, password=password) # Get user from db

            if user is not None:
                auth_login(req, user)
                return redirect('/')
            else:
                messages.info(req, 'Имя пользователя или пароль неправильные')
                return render(req, 'pages/login.html', context)

        return render(req, 'pages/login.html', context)

def logoutUser(req):
    logout(req)
    return redirect('/')

def register(req):
    if req.user.is_authenticated:
        return redirect('/')
    else:
        form = CreateUserForm(use_required_attribute=False)

        if req.method == 'POST':
            form = CreateUserForm(req.POST) # Create new form to check validation
            if form.is_valid():
                user = form.save() # Create new User
                UserProfile.objects.create(id = user.id, user = user) # Create Profile for new User
                username = form.cleaned_data.get('username')
                auth_login(req, user)
                return redirect('/profile/edit')

        context = {'form': form}
        return render(req, 'pages/register.html', context)

# TODO: Move to another .py file
def parseArticleText(text):

    lines = text.splitlines()

    return "\n".join('<p>'+i+'</p>' for i in lines)

blog/templates/auth.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        {% load static %}
        <link rel="stylesheet" href="{% static '/style.css' %}">
        {% block links %}
        {% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

blog/templates/banner.html
<div class="warning-banner">
    <p class="warning-banner__message">Сайт все ещё находится на стадии разработки поэтому некоторые функции могут не работать. Совсем скоро будет добавлена возможность написания статей и лайки.</p>
    <button class="close-banner">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
            <path d="M38 12.83L35.17 10 24 21.17 12.83 10 10 12.83 21.17 24 10 35.17 12.83 38 24 26.83 35.17 38 38 35.17 26.83 24z"/>
        </svg>
    </button>
</div>

<script>
    let btn = document.querySelector('.close-banner')
    btn.onclick = function () {
        this.parentNode.remove();
    }
</script>

blog/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}">
    {% block links %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="header-nav">
            <a href="/" class="logo-a">
                <img src="/media/img/base/logo.png" alt="PolyBlog" class="header-nav__logo">
            </a>
            <div class="header-nav__buttons">
                <input id='search-toggle' type="checkbox" style="display: none;">
                <label for="search-toggle" class="search-toggle">
                    <svg width="25" height="25">
                        <path d="M20.067 18.933l-4.157-4.157a6 6 0 1 0-.884.884l4.157 4.157a.624.624 0 1 0 .884-.884zM6.5 11c0-2.62 2.13-4.75 4.75-4.75S16 8.38 16 11s-2.13 4.75-4.75 4.75S6.5 13.62 6.5 11z"></path>
                    </svg>
                </label>
                <input type="text" name="search" class="search-input" placeholder="Поиск(не работет)">

                {% if request.user.is_anonymous %}
                    <a class="signin-link" href="{% url 'main_app:login' %}">Войти</a>
                {% else %}
                    <input type="checkbox" id="show-menu">
                    <label class="show-menu" for="show-menu">
                        <img src="{{profile.avatar.url}}" alt="Avatar" width="35px" height="35px">
                    </label>
                    <div class="user-menu">
                        <a href="/profile?id={{request.user.id}}" class="user-menu__account">Профиль</a>
                        {% if request.user.is_staff %}
                            <a href="{% url 'admin:index' %}" class="admin">Админ панель</a>
                        {% endif %}
                        <a href="{% url 'main_app:logoutUser' %}" class="logout">Выйти</a>
                    </div>
                {% endif %}

            </div>
        </nav>
    </header>
    <button class="updown">
        <svg width='22px' fill='rgb(179, 175, 175)' height='22px' viewBox="0 0 520 520">
            <g>
                <path d="M145.188,238.575l215.5-215.5c5.3-5.3,5.3-13.8,0-19.1s-13.8-5.3-19.1,0l-225.1,225.1c-5.3,5.3-5.3,13.8,0,19.1l225.1,225 c2.6,2.6,6.1,4,9.5,4s6.9-1.3,9.5-4c5.3-5.3,5.3-13.8,0-19.1L145.188,238.575z"/>
            </g>
        </svg>
    </button>
    {% block content %}{% endblock %}
    {% load static %}
    <script src="{% static '/upbutton.js' %}"></script>
</body>
</html>

blog/templates/filters.html
<div class="wrapper">
    <!-- TODO: Make filters fixed -->
    <div class="filters-wrapper">
        <div class="filters">
            <div class="filters__inner">
                {% for c in categories %}
                {% if c.category_no == category_id %}
                <span class="link-container"><a href="/category?id={{c.category_no}}"
                        class="filters__link active">{{ c.name }}</a></span>
                {% else %}
                <span class="link-container"><a href="/category?id={{c.category_no}}"
                        class="filters__link">{{ c.name }}</a></span>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <a class="prev disabled">
            <svg width="21" height="21">
                <path d="M13.402 16.957l-6.478-6.479L13.402 4l.799.71-5.768 5.768 5.768 5.77z" fill-rule="evenodd">
                </path>
            </svg>
        </a>
        <a class="next">
            <svg width="21" height="21">
                <path d="M8.3 4.2l6.4 6.3-6.4 6.3-.8-.8 5.5-5.5L7.5 5" fill-rule="evenodd"></path>
            </svg>
        </a>
    </div>
</div>