blog/apps/main_app/urls.py
from django.urls import path

from . import views

app_name = 'main_app'
urlpatterns = [
    path('', views.index, name = 'index'),

    path('profile/', views.profile, name = 'profile'),
    path('profile/edit', views.edit_profile, name = 'edit_profile'),

    path('login/', views.login, name = 'login'),
    path('logout/', views.logoutUser, name = 'logoutUser'),
    path('register/', views.register, name = 'register'),

    path('category/', views.category, name = 'category'),
    path('article/', views.article, name = 'article'),
    path('loadArticles/', views.loadArticles, name = 'loadArticles'),

    path('article/<int:article_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
    path('loadComments/', views.loadComments, name = 'loadComments'),
    path('deleteComment/', views.deleteComment, name = 'deleteComment')
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main_app.urls')),
    path(r'supers3cret4dm1n/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/main_app/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.conf import settings

from django.contrib.auth.models import User

from PIL import Image

import os
from django.db.models.signals import pre_save
from django.dispatch.dispatcher import receiver

class UserProfile(models.Model):

    user   = models.OneToOneField(User, on_delete=models.CASCADE)
    bio    = models.CharField('Описание пользователя', max_length=170)
    avatar = models.ImageField(upload_to='img/users', max_length=100, default='img/default_images/defaultUser.png')

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save()

        img  = Image.open(self.avatar.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)  
            img.save(self.avatar.path)

class Category(models.Model):
    category_no   = models.IntegerField('Номер категории', primary_key=True)
    name          = models.CharField('Название категории', max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class Article(models.Model):
    article_image       = models.ImageField(upload_to='img/articles', max_length=100, default='img/default_images/default.jpg')
    article_title       = models.CharField('Название статьи', max_length = 30)
    article_description = models.CharField('Краткое описание статьи', max_length = 150)
    article_text        = models.TextField('Текст статьи')
    pub_date            = models.DateTimeField('Дата публикации')
    is_main_in_category = models.BooleanField('Главная статья в своей категории(можно поставить только 1)', default=False)
    is_main_in_homepage = models.BooleanField('Главная статья на домашней страницу(всего 3)', default=False)
    author              = models.ForeignKey(UserProfile, on_delete = models.CASCADE)
    category            = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, db_column='category_no', default=14)
    likes               = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.is_main_in_category:
            try:
                temp = Article.objects.get(is_main_in_category=True, category=self.category)
                if self != temp:
                    temp.is_main_in_category = False
                    temp.save()
            except Article.DoesNotExist:
                pass

        if self.is_main_in_homepage:
            try:
                main_count = len(Article.objects.filter(is_main_in_homepage=True))
                if main_count >= 3:
                    self.is_main_in_homepage = False
            except Article.DoesNotExist:
                pass
            
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

    # For russian lang
    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

class Comment(models.Model):
    article      = models.ForeignKey(Article, on_delete = models.CASCADE)
    
    author       = models.ForeignKey(UserProfile, on_delete = models.CASCADE)
    comment_text = models.CharField('Текст комментария', max_length = 200)
    pub_date     = models.DateTimeField('Дата публикации')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

# Delete images from media folder when they uploaded
@receiver(pre_save, sender=UserProfile)
def delete_avatar(sender, instance, *args, **kwargs):
    try:
        old_instance = UserProfile.objects.get(id=instance.id)
        old_avatar = os.path.basename(old_instance.avatar.name)
        new_avatar = os.path.basename(instance.avatar.name)

        if (old_avatar != new_avatar):
            if (old_avatar != 'defaultUser.png'):
                os.remove(old_instance.avatar.path)
            
    except UserProfile.DoesNotExist:
        return None

@receiver(pre_save, sender=Article)
def delete_img(sender, instance, *args, **kwargs):
    try:
        old_instance = Article.objects.get(id=instance.id)
        old_image = os.path.basename(old_instance.article_image.name)
        new_image = os.path.basename(instance.article_image.name)

        if (new_image != old_image):
            if (old_image != 'default.jpg'):
                os.remove(old_instance.article_image.path)
            
    except Article.DoesNotExist:
        return None

blog/apps/main_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from main_app.models import UserProfile

class CreateUserForm(UserCreationForm):
    username = forms.CharField(error_messages={'required': 'Введите имя пользователя'})
    
    error_messages = {
        'password_mismatch': ("Пароли не совпадают"),
    }

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'username-edit'})
        }

class ProfileUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)

        self.fields['bio'].required = False

    class Meta:
        model = UserProfile
        fields = ['bio', 'avatar']
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'bio-edit', 'maxlength': '170', 'placeholder': 'Введите короткое описание'})
        }

blog/apps/main_app/views.py
# TODO: Make like button
# TODO: Customizate admin panel
# TODO: Make ability to create, update and delete articles

import json

from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404

from django.utils import timezone

from .models import Category, Article, Comment, UserProfile

from .forms import CreateUserForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib import messages

from django.contrib.auth.decorators import login_required

from django import forms

def index(req):

    categories          = Category.objects.all()
    main_articles       = Article.objects.filter(is_main_in_homepage=True).order_by('likes') # Get three main articles and order by likes
    main_articles_array = main_articles[1:]

    popular_articles = Article.objects.order_by('-likes')[:10]

    context = {
        'categories': categories,
        'main_article': main_articles[0],
        'articles': popular_articles, 
        'main_articles': main_articles_array
    }

    if req.user.is_authenticated:
        profile = UserProfile.objects.get(user = req.user)
        context['profile'] = profile

    return render(req, 'pages/index.html', context)

def category(req):

    categories   = Category.objects.all()
    id           = req.GET.get('id')
    current_cat  = Category.objects.get(category_no = id)
    articles     = Article.objects.filter(category_id = id).order_by('-likes')[:9]
    
    try:
        main_article = Article.objects.get(category_id = id, is_main_in_category = True)    
    except Article.DoesNotExist:
        main_article = None
    
    context = {
        'categories': categories, 
        'articles': articles, 
        'main_article': main_article, 
        'current_cat': current_cat, 
        'category_id': int(id)
    }

    if req.user.is_authenticated:
        profile = UserProfile.objects.get(user = req.user)
        context['profile'] = profile

    return render(req, 'pages/category.html', context)

def loadArticles(req):
    count = req.GET.get('count', 10)
    id    = req.GET.get('id')
    count = int(count)

    if id is not None:
        id = int(id)
        popular_articles = Article.objects.filter(is_main_in_category=False, category_id = id).order_by('-likes')[count:count+9]
    else:
        popular_articles = Article.objects.filter(is_main_in_homepage=False).order_by('-likes')[count:count+10]

    response_data = []

    for a in popular_articles:
        article                = {}
        article["id"]          = a.id
        article["img"]         = a.article_image.url
        article["title"]       = a.article_title
        article["desc"]        = a.article_description
        article["author_name"] = a.author.user.username
        article["author_id"]   = a.author.id
        article["date"]        = a.pub_date.strftime("%d %B %Y %H:%M")
        article["category"]    = a.category.name
        article["category_no"] = a.category.category_no
        article["likes"]       = a.likes

        response_data.append(article)

    context = json.dumps(response_data)

    return HttpResponse(context, content_type="application/json")

def article(req):

    id         = req.GET.get('id')
    categories = Category.objects.all()
   
    try:
        article        = Article.objects.get(id = id)
        profile        = UserProfile.objects.get(id = article.author.id)
    except:
        raise Http404('Статья не найдена')

    latest_comments_list = article.comment_set.order_by('-id')[:10]
    comment_count        = article.comment_set.count()
    
    article.article_text = parseArticleText(article.article_text)

    context = {
        'article': article, 
        'categories': categories, 
        'category_id': article.category_id, 
        'comments': latest_comments_list, 
        'author_profile': profile,
        'comment_count': comment_count
    }

    if req.user.is_authenticated:
        currentProfile = UserProfile.objects.get(user = req.user)
        context['profile'] = currentProfile

    return render(req, 'pages/article.html', context)


def profile(req):

    id      = req.GET.get('id')
    profile = UserProfile.objects.get(user = req.user)

    try:
        user_profile = UserProfile.objects.get(id = id)
    except:
        raise Http404('Пользователь не найден')

    last_articles = Article.objects.filter(author = user_profile).order_by('-pub_date')
    last_comments = Comment.objects.filter(author = user_profile).order_by('-pub_date')

    if (last_articles):
        last_articles = last_articles[0:8]

    if (last_comments):
        last_comments = last_comments[0:4]

    return render(req, 'user/profile.html', {'lastArticles': last_articles, 'lastComments': last_comments, 'profile': profile, 'load_profile': user_profile})

@login_required
def edit_profile(req):

    profile = UserProfile.objects.get(user = req.user)

    if req.method == 'POST':

        u_form = UserUpdateForm(req.POST, instance = req.user)
        p_form = ProfileUpdateForm(req.POST, req.FILES, instance = profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(req, 'Ваш аккаунт обновлен')
            return redirect('/profile/edit')

    else:
        u_form = UserUpdateForm(instance = req.user)
        p_form = ProfileUpdateForm(instance = profile)

    context = {'u_form': u_form, 'p_form': p_form, 'profile': profile}

    return render(req, 'user/edit.html', context)


def leave_comment(req, article_id):

    if req.user.is_authenticated:

        try:
            a = Article.objects.get(id = article_id)
        except:
            raise Http404("Статья не найдена")

        data = json.loads(req.body)
        profile = UserProfile.objects.get(user = req.user)
        
        c = a.comment_set.create(author = profile, comment_text = data['text'], pub_date = timezone.now())

        comment                = {}
        comment["id"]          = c.id
        comment["image"]       = c.author.avatar.url
        comment["author_name"] = c.author.user.username
        comment["author_id"]   = c.author.user.id
        comment["show-delete"] = True
        comment["pub_date"]    = c.pub_date.strftime("%d %B %Y %H:%M")
        comment["text"]        = c.comment_text

        context = json.dumps(comment)

        return HttpResponse(context, content_type="application/json")

    else:
        jsonr = json.dumps({ 'authenticated': False })
        return HttpResponse(jsonr, content_type="application/json")

def loadComments(req):

    count = req.GET.get('count', 10)
    count = int(count)

    latest_comments = Comment.objects.order_by('-id')[count:count+10]

    response_data = []

    for c in latest_comments:
        comment                = {}
        comment["id"]          = c.id
        comment["image"]       = c.author.avatar.url
        comment["author_name"] = c.author.user.username
        comment["author_id"]   = c.author.user.id
        comment["pub_date"]    = c.pub_date.strftime("%d %B %Y %H:%M")
        comment["text"]        = c.comment_text

        if c.author.user == req.user:
            comment["show-delete"] = True
        else:
            comment["show-delete"] = False

        response_data.append(comment)

    context = json.dumps(response_data)

    return HttpResponse(context, content_type="application/json")

def deleteComment(req):

    id = req.GET.get('id')

    Comment.objects.filter(id = id).delete()

    jsonr = json.dumps({ 'deleted': True })
    return HttpResponse(jsonr, content_type="application/json")


def login(req):

    if req.user.is_authenticated:
        return redirect('/')
    else:
        context = {}

        if req.method == 'POST':
            username = req.POST["username"]
            password = req.POST["password"]

            user = authenticate(req, username=username, password=password) # Get user from db

            if user is not None:
                auth_login(req, user)
                return redirect('/')
            else:
                messages.info(req, 'Имя пользователя или пароль неправильные')
                return render(req, 'pages/login.html', context)

        return render(req, 'pages/login.html', context)

def logoutUser(req):
    logout(req)
    return redirect('/')

def register(req):
    if req.user.is_authenticated:
        return redirect('/')
    else:
        form = CreateUserForm(use_required_attribute=False)

        if req.method == 'POST':
            form = CreateUserForm(req.POST) # Create new form to check validation
            if form.is_valid():
                user = form.save() # Create new User
                UserProfile.objects.create(id = user.id, user = user) # Create Profile for new User
                username = form.cleaned_data.get('username')
                auth_login(req, user)
                return redirect('/profile/edit')

        context = {'form': form}
        return render(req, 'pages/register.html', context)

# TODO: Move to another .py file
def parseArticleText(text):

    lines = text.splitlines()

    return "\n".join('<p>'+i+'</p>' for i in lines)

blog/templates/user/edit.html
{% extends 'base.html' %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/profile.css' %}">
{% endblock %}

{% block title %}Редактировать профиль{% endblock %}

{% block content %}
    <div class="wrapper">

        {% for message in messages %}
            <p class='message'>{{message}}</p>
        {% endfor %}
        {% if u_form.username.errors %}
            <p class='error-message'>{{ u_form.username.errors.as_text }}</p>
        {% endif %}
        {% if p_form.bio.errors %}
            <p class='error-message'>{{ p_form.bio.errors.as_text }}</p>
        {% endif %}
        {% if p_form.avatar.errors %}
            <p class='error-message'>{{ p_form.avatar.errors.as_text }}</p>
        {% endif %}

        <form action="/profile/edit" class="edit-form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="user">
                <div class="user__info">
                    <div class="user__info-top">
                        {{ u_form.username }}
                    </div>
                    <p class="user__info-bio">
                        {{ p_form.bio }}
                    </p>
                    <div class="buttons">
                        <button class="save" type="submit">Сохранить</button>
                        <a href="/profile?id={{ request.user.id }}" class="close">Закрыть</a>
                    </div>
                </div>
                <div class="user__avatar">
                    <div class="user__avatar-data" style="display: none;">
                        {{ p_form.avatar }}
                    </div>
                    <img class="user__avatar-img brightless" src="{{profile.avatar.url}}" alt="Avatar">
                    <label for="id_avatar" class="change-photo">
                        <svg class="svg-photo">
                            <g fill-rule="evenodd">
                                <path d="M10.61 44.486V23.418c0-2.798 2.198-4.757 5.052-4.757h6.405c1.142-1.915 2.123-5.161 3.055-5.138L40.28 13.5c.79 0 1.971 3.4 3.073 5.14 0 .2 6.51 0 6.51 0 2.856 0 5.136 1.965 5.136 4.757V44.47c-.006 2.803-2.28 4.997-5.137 4.997h-34.2c-2.854.018-5.052-2.184-5.052-4.981zm5.674-23.261c-1.635 0-3.063 1.406-3.063 3.016v19.764c0 1.607 1.428 2.947 3.063 2.947H49.4c1.632 0 2.987-1.355 2.987-2.957v-19.76c0-1.609-1.357-3.016-2.987-3.016h-7.898c-.627-1.625-1.909-4.937-2.28-5.148 0 0-13.19.018-13.055 0-.554.276-2.272 5.143-2.272 5.143l-7.611.01z"></path>
                                <path d="M32.653 41.727c-5.06 0-9.108-3.986-9.108-8.975 0-4.98 4.047-8.966 9.108-8.966 5.057 0 9.107 3.985 9.107 8.969 0 4.988-4.047 8.974-9.107 8.974v-.002zm0-15.635c-3.674 0-6.763 3.042-6.763 6.66 0 3.62 3.089 6.668 6.763 6.668 3.673 0 6.762-3.047 6.762-6.665 0-3.616-3.088-6.665-6.762-6.665v.002z"></path>
                            </g>
                        </svg>
                    </label>
                </div>
            </div>
        </form>
    </div>
    <script src="{% static '/profile.js' %}"></script>
{% endblock %}

blog/templates/user/profile.html
{% extends 'base.html' %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/profile.css' %}">
{% endblock %}

{% block title %}Профиль{% endblock %}

{% block content %}
    <div class="wrapper">
        <a href="/" class="back-home">На главную</a>
        <div class="user">
            <div class="user__info">
                <div class="user__info-top">
                    <h1 class="user__info-name">{{load_profile.user}}</h1>
                    {% if request.user == load_profile.user %}
                        <a class="edit-profile" href="/profile/edit">Редактировать</a>
                    {% endif %}
                </div>
                <p class="user__info-bio">
                    {% if load_profile.bio %}
                        {{load_profile.bio}}
                    {% else %}
                        <p class="add_bio">Пользователь не добавил описание</p>
                    {% endif %}
                </p>
            </div>
            <div class="user__avatar">
                <img class="user__avatar-img" src="{{load_profile.avatar.url}}" alt="Avatar">
            </div>
        </div>
        <div class="user_content">
            <div class="articles">
                <h3 class="articles__title">Последние статьи</h3>
                
                {% if lastArticles %}
                    {% for a in lastArticles %}
                
                        <div class="article">
                            <a href="/article?id={{a.id}}" class="article__image">
                                <img src="{{ a.article_image.url }}" class="article__image-img" alt="article image">
                            </a>
                            <a href="/article?id={{a.id}}" class="article__title">{{ a.article_title }}</a>
                            <a href="/article?id={{a.id}}" class="article__desc">{{ a.article_description }}</a>
                            <div class="article__meta">
                                <button class="like-btn">
                                    <svg height="24" version="1.1" width="24">
                                        <g transform="translate(0 -1028.4)">
                                            <path d="m7 1031.4c-1.5355 0-3.0784 0.5-4.25 1.7-2.3431 2.4-2.2788 6.1 0 8.5l9.25 9.8 9.25-9.8c2.279-2.4 2.343-6.1 0-8.5-2.343-2.3-6.157-2.3-8.5 0l-0.75 0.8-0.75-0.8c-1.172-1.2-2.7145-1.7-4.25-1.7z" fill="#c0392b"/>
                                        </g>
                                    </svg>
                                    <span>{{ a.likes }}</span>
                                </button>
                                <p class="article__date">{{ a.pub_date }}</p>
                            </div>
                        </div>

                    {% endfor %}
                {% else %}
                    <p>Не найдены</p>
                {% endif %}
                
            </div>
            <div class="comments">
                <h3 class="comments__title">Последние комментарии</h3>
                {% if lastComments %}
                    {% for c in lastComments %}
                        <div class="comment">
                            <p class="comment-text">{{ c.comment_text }}</p>
                            <a href="/article?id={{ c.article.id }}" class='comment__link' href="">Перейти к статье</a>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>Не найдены</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}