blog/apps/main_app/urls.py
from django.urls import path

from . import views

app_name = 'main_app'
urlpatterns = [
    path('', views.index, name = 'index'),

    path('profile/', views.profile, name = 'profile'),
    path('profile/edit', views.edit_profile, name = 'edit_profile'),

    path('login/', views.login, name = 'login'),
    path('logout/', views.logoutUser, name = 'logoutUser'),
    path('register/', views.register, name = 'register'),

    path('category/', views.category, name = 'category'),
    path('article/', views.article, name = 'article'),
    path('loadArticles/', views.loadArticles, name = 'loadArticles'),

    path('article/<int:article_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
    path('loadComments/', views.loadComments, name = 'loadComments'),
    path('deleteComment/', views.deleteComment, name = 'deleteComment')
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main_app.urls')),
    path(r'supers3cret4dm1n/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/main_app/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.conf import settings

from django.contrib.auth.models import User

from PIL import Image

import os
from django.db.models.signals import pre_save
from django.dispatch.dispatcher import receiver

class UserProfile(models.Model):

    user   = models.OneToOneField(User, on_delete=models.CASCADE)
    bio    = models.CharField('Описание пользователя', max_length=170)
    avatar = models.ImageField(upload_to='img/users', max_length=100, default='img/default_images/defaultUser.png')

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save()

        img  = Image.open(self.avatar.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)  
            img.save(self.avatar.path)

class Category(models.Model):
    category_no   = models.IntegerField('Номер категории', primary_key=True)
    name          = models.CharField('Название категории', max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class Article(models.Model):
    article_image       = models.ImageField(upload_to='img/articles', max_length=100, default='img/default_images/default.jpg')
    article_title       = models.CharField('Название статьи', max_length = 30)
    article_description = models.CharField('Краткое описание статьи', max_length = 150)
    article_text        = models.TextField('Текст статьи')
    pub_date            = models.DateTimeField('Дата публикации')
    is_main_in_category = models.BooleanField('Главная статья в своей категории(можно поставить только 1)', default=False)
    is_main_in_homepage = models.BooleanField('Главная статья на домашней страницу(всего 3)', default=False)
    author              = models.ForeignKey(UserProfile, on_delete = models.CASCADE)
    category            = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, db_column='category_no', default=14)
    likes               = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.is_main_in_category:
            try:
                temp = Article.objects.get(is_main_in_category=True, category=self.category)
                if self != temp:
                    temp.is_main_in_category = False
                    temp.save()
            except Article.DoesNotExist:
                pass

        if self.is_main_in_homepage:
            try:
                main_count = len(Article.objects.filter(is_main_in_homepage=True))
                if main_count >= 3:
                    self.is_main_in_homepage = False
            except Article.DoesNotExist:
                pass
            
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

    # For russian lang
    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

class Comment(models.Model):
    article      = models.ForeignKey(Article, on_delete = models.CASCADE)
    
    author       = models.ForeignKey(UserProfile, on_delete = models.CASCADE)
    comment_text = models.CharField('Текст комментария', max_length = 200)
    pub_date     = models.DateTimeField('Дата публикации')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

# Delete images from media folder when they uploaded
@receiver(pre_save, sender=UserProfile)
def delete_avatar(sender, instance, *args, **kwargs):
    try:
        old_instance = UserProfile.objects.get(id=instance.id)
        old_avatar = os.path.basename(old_instance.avatar.name)
        new_avatar = os.path.basename(instance.avatar.name)

        if (old_avatar != new_avatar):
            if (old_avatar != 'defaultUser.png'):
                os.remove(old_instance.avatar.path)
            
    except UserProfile.DoesNotExist:
        return None

@receiver(pre_save, sender=Article)
def delete_img(sender, instance, *args, **kwargs):
    try:
        old_instance = Article.objects.get(id=instance.id)
        old_image = os.path.basename(old_instance.article_image.name)
        new_image = os.path.basename(instance.article_image.name)

        if (new_image != old_image):
            if (old_image != 'default.jpg'):
                os.remove(old_instance.article_image.path)
            
    except Article.DoesNotExist:
        return None

blog/apps/main_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from main_app.models import UserProfile

class CreateUserForm(UserCreationForm):
    username = forms.CharField(error_messages={'required': 'Введите имя пользователя'})
    
    error_messages = {
        'password_mismatch': ("Пароли не совпадают"),
    }

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'username-edit'})
        }

class ProfileUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)

        self.fields['bio'].required = False

    class Meta:
        model = UserProfile
        fields = ['bio', 'avatar']
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'bio-edit', 'maxlength': '170', 'placeholder': 'Введите короткое описание'})
        }

blog/apps/main_app/views.py
# TODO: Make like button
# TODO: Customizate admin panel
# TODO: Make ability to create, update and delete articles

import json

from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404

from django.utils import timezone

from .models import Category, Article, Comment, UserProfile

from .forms import CreateUserForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib import messages

from django.contrib.auth.decorators import login_required

from django import forms

def index(req):

    categories          = Category.objects.all()
    main_articles       = Article.objects.filter(is_main_in_homepage=True).order_by('likes') # Get three main articles and order by likes
    main_articles_array = main_articles[1:]

    popular_articles = Article.objects.order_by('-likes')[:10]

    context = {
        'categories': categories,
        'main_article': main_articles[0],
        'articles': popular_articles, 
        'main_articles': main_articles_array
    }

    if req.user.is_authenticated:
        profile = UserProfile.objects.get(user = req.user)
        context['profile'] = profile

    return render(req, 'pages/index.html', context)

def category(req):

    categories   = Category.objects.all()
    id           = req.GET.get('id')
    current_cat  = Category.objects.get(category_no = id)
    articles     = Article.objects.filter(category_id = id).order_by('-likes')[:9]
    
    try:
        main_article = Article.objects.get(category_id = id, is_main_in_category = True)    
    except Article.DoesNotExist:
        main_article = None
    
    context = {
        'categories': categories, 
        'articles': articles, 
        'main_article': main_article, 
        'current_cat': current_cat, 
        'category_id': int(id)
    }

    if req.user.is_authenticated:
        profile = UserProfile.objects.get(user = req.user)
        context['profile'] = profile

    return render(req, 'pages/category.html', context)

def loadArticles(req):
    count = req.GET.get('count', 10)
    id    = req.GET.get('id')
    count = int(count)

    if id is not None:
        id = int(id)
        popular_articles = Article.objects.filter(is_main_in_category=False, category_id = id).order_by('-likes')[count:count+9]
    else:
        popular_articles = Article.objects.filter(is_main_in_homepage=False).order_by('-likes')[count:count+10]

    response_data = []

    for a in popular_articles:
        article                = {}
        article["id"]          = a.id
        article["img"]         = a.article_image.url
        article["title"]       = a.article_title
        article["desc"]        = a.article_description
        article["author_name"] = a.author.user.username
        article["author_id"]   = a.author.id
        article["date"]        = a.pub_date.strftime("%d %B %Y %H:%M")
        article["category"]    = a.category.name
        article["category_no"] = a.category.category_no
        article["likes"]       = a.likes

        response_data.append(article)

    context = json.dumps(response_data)

    return HttpResponse(context, content_type="application/json")

def article(req):

    id         = req.GET.get('id')
    categories = Category.objects.all()
   
    try:
        article        = Article.objects.get(id = id)
        profile        = UserProfile.objects.get(id = article.author.id)
    except:
        raise Http404('Статья не найдена')

    latest_comments_list = article.comment_set.order_by('-id')[:10]
    comment_count        = article.comment_set.count()
    
    article.article_text = parseArticleText(article.article_text)

    context = {
        'article': article, 
        'categories': categories, 
        'category_id': article.category_id, 
        'comments': latest_comments_list, 
        'author_profile': profile,
        'comment_count': comment_count
    }

    if req.user.is_authenticated:
        currentProfile = UserProfile.objects.get(user = req.user)
        context['profile'] = currentProfile

    return render(req, 'pages/article.html', context)


def profile(req):

    id      = req.GET.get('id')
    profile = UserProfile.objects.get(user = req.user)

    try:
        user_profile = UserProfile.objects.get(id = id)
    except:
        raise Http404('Пользователь не найден')

    last_articles = Article.objects.filter(author = user_profile).order_by('-pub_date')
    last_comments = Comment.objects.filter(author = user_profile).order_by('-pub_date')

    if (last_articles):
        last_articles = last_articles[0:8]

    if (last_comments):
        last_comments = last_comments[0:4]

    return render(req, 'user/profile.html', {'lastArticles': last_articles, 'lastComments': last_comments, 'profile': profile, 'load_profile': user_profile})

@login_required
def edit_profile(req):

    profile = UserProfile.objects.get(user = req.user)

    if req.method == 'POST':

        u_form = UserUpdateForm(req.POST, instance = req.user)
        p_form = ProfileUpdateForm(req.POST, req.FILES, instance = profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(req, 'Ваш аккаунт обновлен')
            return redirect('/profile/edit')

    else:
        u_form = UserUpdateForm(instance = req.user)
        p_form = ProfileUpdateForm(instance = profile)

    context = {'u_form': u_form, 'p_form': p_form, 'profile': profile}

    return render(req, 'user/edit.html', context)


def leave_comment(req, article_id):

    if req.user.is_authenticated:

        try:
            a = Article.objects.get(id = article_id)
        except:
            raise Http404("Статья не найдена")

        data = json.loads(req.body)
        profile = UserProfile.objects.get(user = req.user)
        
        c = a.comment_set.create(author = profile, comment_text = data['text'], pub_date = timezone.now())

        comment                = {}
        comment["id"]          = c.id
        comment["image"]       = c.author.avatar.url
        comment["author_name"] = c.author.user.username
        comment["author_id"]   = c.author.user.id
        comment["show-delete"] = True
        comment["pub_date"]    = c.pub_date.strftime("%d %B %Y %H:%M")
        comment["text"]        = c.comment_text

        context = json.dumps(comment)

        return HttpResponse(context, content_type="application/json")

    else:
        jsonr = json.dumps({ 'authenticated': False })
        return HttpResponse(jsonr, content_type="application/json")

def loadComments(req):

    count = req.GET.get('count', 10)
    count = int(count)

    latest_comments = Comment.objects.order_by('-id')[count:count+10]

    response_data = []

    for c in latest_comments:
        comment                = {}
        comment["id"]          = c.id
        comment["image"]       = c.author.avatar.url
        comment["author_name"] = c.author.user.username
        comment["author_id"]   = c.author.user.id
        comment["pub_date"]    = c.pub_date.strftime("%d %B %Y %H:%M")
        comment["text"]        = c.comment_text

        if c.author.user == req.user:
            comment["show-delete"] = True
        else:
            comment["show-delete"] = False

        response_data.append(comment)

    context = json.dumps(response_data)

    return HttpResponse(context, content_type="application/json")

def deleteComment(req):

    id = req.GET.get('id')

    Comment.objects.filter(id = id).delete()

    jsonr = json.dumps({ 'deleted': True })
    return HttpResponse(jsonr, content_type="application/json")


def login(req):

    if req.user.is_authenticated:
        return redirect('/')
    else:
        context = {}

        if req.method == 'POST':
            username = req.POST["username"]
            password = req.POST["password"]

            user = authenticate(req, username=username, password=password) # Get user from db

            if user is not None:
                auth_login(req, user)
                return redirect('/')
            else:
                messages.info(req, 'Имя пользователя или пароль неправильные')
                return render(req, 'pages/login.html', context)

        return render(req, 'pages/login.html', context)

def logoutUser(req):
    logout(req)
    return redirect('/')

def register(req):
    if req.user.is_authenticated:
        return redirect('/')
    else:
        form = CreateUserForm(use_required_attribute=False)

        if req.method == 'POST':
            form = CreateUserForm(req.POST) # Create new form to check validation
            if form.is_valid():
                user = form.save() # Create new User
                UserProfile.objects.create(id = user.id, user = user) # Create Profile for new User
                username = form.cleaned_data.get('username')
                auth_login(req, user)
                return redirect('/profile/edit')

        context = {'form': form}
        return render(req, 'pages/register.html', context)

# TODO: Move to another .py file
def parseArticleText(text):

    lines = text.splitlines()

    return "\n".join('<p>'+i+'</p>' for i in lines)

blog/templates/pages/article.html
{% extends 'base.html' %}

{% block links %}
    {% load static %}
	<link rel="stylesheet" href="{% static '/articlePage.css' %}">
{% endblock %}

{% block title %}{{ article.article_title }}{% endblock %}

{% block content %}
    {% include 'filters.html' %}
    <div class="wrapper">
        <div class="article">
            <h1 class="article__title">{{article.article_title}}</h1>
            <p class="article__desc">{{article.article_description}}</p>
            <div class="about_author">
                <a href="/profile?id={{article.author.id}}" class="avatar">
                    <img src="{{author_profile.avatar.url}}" alt="Avatar">
                </a>
                <div class="author-info">
                    <a href="/profile?id={{article.author.id}}" class="author-info__name">{{author_profile.user}}</a>
                    <span class="date">{{article.pub_date}}</span>
                </div>
            </div>
            <img src="{{article.article_image.url}}" alt="Article image" class="article_img">
            <div class="article__text">
                {{article.article_text |safe}}
            </div>
            <button class="like-btn">
                <svg height="24" version="1.1" width="24">
                    <g transform="translate(0 -1028.4)">
                        <path
                            d="m7 1031.4c-1.5355 0-3.0784 0.5-4.25 1.7-2.3431 2.4-2.2788 6.1 0 8.5l9.25 9.8 9.25-9.8c2.279-2.4 2.343-6.1 0-8.5-2.343-2.3-6.157-2.3-8.5 0l-0.75 0.8-0.75-0.8c-1.172-1.2-2.7145-1.7-4.25-1.7z"
                            fill="#c0392b" />
                    </g>
                </svg>
                <span>{{ article.likes }}</span>
            </button>
        </div>
    </div>
    <div class="comments-wrapper">
        <div class="wrapper">
            <div class="comments">
                <h3 class="comments__title">Комментариев: {{ comment_count }}</h3>

                <form class="comments__form">
                    
                    <div class="avatar">
                        {% if request.user.is_anonymous %}
                            <img src="/media/img/default_images/defaultUser.png" alt="">
                        {% else %}
                            <img src="{{profile.avatar.url}}" alt="">
                        {% endif %}
                    </div>

                    <textarea class="comments__form-textarea" name="text" placeholder="Напишите комментарий" maxlength = "200"></textarea>
                    <button class="comments__form-btn" type="submit">Опубликовать</button>
                
                </form>
        
                {% if comments %}
                    
                    {% for comment in comments %}
                        <div class="comment" data-id="{{comment.id}}">
                            <div class="comment__about_author">
                                <div class="about_author-wrap">
                                    <a href="/profile?id={{comment.author.id}}" class="avatar">
                                        <img src="{{comment.author.avatar.url}}" alt="">
                                    </a>
                                    <div class="author-info">
                                        <a href="/profile?id={{comment.author.id}}" class="author-info__name">{{comment.author}}</a>
                                        <span class="date">{{comment.pub_date}}</span>
                                    </div>
                                </div>
                                {% if user == comment.author.user %}
                                <p title = 'Удалить комментарий' style="margin: 0;">
                                    <svg class="delete_comment" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
                                        <path d="M38 12.83L35.17 10 24 21.17 12.83 10 10 12.83 21.17 24 10 35.17 12.83 38 24 26.83 35.17 38 38 35.17 26.83 24z"/>
                                    </svg>
                                </p>
                                {% endif %}
                            </div>
                            <p class="comment-text">{{ comment.comment_text }}</p>
                        </div>
                    {% endfor %}
            
                {% else %}
                    <p class='no-comments'>Комментарии не найдены. Станьте первым</p>
                {% endif %}

                <button class="load-btn">
                    Загрузить ещё
                    <svg width="21" height="21" viewBox="0 0 21 21">
                        <path d="M4 7.33L10.03 14l.5.55.5-.55 5.96-6.6-.98-.9-5.98 6.6h1L4.98 6.45z" fill-rule="evenodd"></path>
                    </svg>
                </button>

            </div>
        </div>
    </div>
    <footer>
        <p class="footer__info">© 2020 Yurkin Ivan | Dev version</p>
    </footer>

    {% load static %}
    <script src="{% static '/article.js' %}"></script>
    <script src="{% static '/filterSlider.js' %}"></script>

{% endblock %}

blog/templates/pages/category.html
{% extends 'base.html' %}

{% block links %}
	{% load static %}
	<link rel="stylesheet" href="{% static '/category.css' %}">
{% endblock links %}

{% block title %} {{current_cat}} {% endblock title %}

{% block content %}
	{% include 'filters.html' %}
	<div class="wrapper">
		<h1 class="title">{{current_cat}}</h1>
		{% if main_article %}
			<div class="main_article">
				<a href="/article?id={{main_article.id}}" class="main_article__image-wrap">
					<img src="{{ main_article.article_image.url }}" alt="article image" class="main_article__image">
				</a>
				<div class="main_article__content">
					<a href="/article?id={{main_article.id}}" class="main_article__title">{{main_article.article_title}}</a>
					<a href="/article?id={{main_article.id}}" class="main_article__desc">{{main_article.article_description}}</a>
					<a href="/profile?id={{main_article.author.id}}" class="main_article__author-name">{{ main_article.author }}</a>
					<span class="main_article__date">{{ main_article.pub_date }}</span>
				</div>
			</div>
		{% endif %}
		<div class="article-wrapper">

			{% if articles %}
				{% for a in articles %}

					{% if not a.is_main_in_category %}

						<div class="article">
							<a href="/article?id={{a.id}}"><img src="{{ a.article_image.url }}" alt="Article image" class="article__img"></a>
							<div class="article__content">
								<a href="/article?id={{a.id}}" class="article__title">{{ a.article_title }}</a>
								<a href="/article?id={{a.id}}">
									<p class="article__desc">{{ a.article_description }}</p>
								</a>
								<a href="/profile?id={{a.author.id}}" class="article__author-name">{{ a.author }}</a>
								<p class="article__date">{{ a.pub_date }}</p>
								<button class="like-btn">
									<svg height="24" version="1.1" width="24">
										<g transform="translate(0 -1028.4)">
											<path
												d="m7 1031.4c-1.5355 0-3.0784 0.5-4.25 1.7-2.3431 2.4-2.2788 6.1 0 8.5l9.25 9.8 9.25-9.8c2.279-2.4 2.343-6.1 0-8.5-2.343-2.3-6.157-2.3-8.5 0l-0.75 0.8-0.75-0.8c-1.172-1.2-2.7145-1.7-4.25-1.7z"
												fill="#c0392b" />
										</g>
									</svg>
									<span>{{ a.likes }}</span>
								</button>
							</div>
						</div>

					{% endif %}

				{% endfor %}
				<button class="load-btn">
					Загрузить ещё
					<svg width="21" height="21" viewBox="0 0 21 21">
						<path d="M4 7.33L10.03 14l.5.55.5-.55 5.96-6.6-.98-.9-5.98 6.6h1L4.98 6.45z" fill-rule="evenodd"></path>
					</svg>
				</button>
			{% else %}
				<p class="error">Статей в этой категории не найдено</p>
			{% endif %}
		</div>
	</div>
	<footer>
        <p class="footer__info">© 2020 Yurkin Ivan | Dev version</p>
    </footer>
	{% load static %}
    <script src="{% static '/category.js' %}"></script>
	<script src="{% static '/filterSlider.js' %}"></script>
{% endblock content %}

blog/templates/pages/index.html
{% extends 'base.html' %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/home.css' %}">
    <link rel="stylesheet" href="{% static '/banner.css' %}">
{% endblock links %}

{% block title %} Главная {% endblock title %}

{% block content %}
    {% include 'filters.html' %}
    {% include 'banner.html' %}
    <div class="wrapper">
        <div class="popular-wrapper">

            {% if main_article %}

                <div class="popular-wrapper__most-popular">
                    <h1 class="main-title">Popular on our blog</h1>
                    <div class="popular-article">
                        <a href="/article?id={{main_article.id}}" class="popular-article__image-wrap"><img src=" {{ main_article.article_image.url }} " alt="Article image" class="popular-article__img"></a>
                        <a href="/article?id={{main_article.id}}" class="popular-article__title">{{ main_article.article_title }}</a>
                        <a href="/article?id={{main_article.id}}"><p class="popular-article__desc">{{ main_article.article_description }}</p></a>
                        <a href="/profile?id={{main_article.author.id}}" class="popular-article__author-name">{{ main_article.author }}</a>
                        <span class="popular-article__date">{{ main_article.pub_date }}</span>
                        <a href="/category?id={{main_article.category_id}}" class="article-category">{{ main_article.category }}</a>
                    </div>
                </div>

            {% endif %}

            <div class="popular-wrapper__less-popular">
                
                {% if main_articles %}
                    {% for a in main_articles %}

                        <div class="popular-article">
                            <a href="/article?id={{a.id}}" class="popular-article__image-wrap"><img src="{{ a.article_image.url }}" alt="Article image" class="popular-article__img"></a>
                            <a href="/article?id={{a.id}}" class="popular-article__title">{{a.article_title}}</a>
                            <a href="/article?id={{a.id}}"><p class="popular-article__desc">{{a.article_description}}</p></a>
                            <a href="/profile?id={{a.author.id}}" class="popular-article__author-name">{{a.author}}</a>
                            <span class="popular-article__date">{{a.pub_date}}</span>
                            <a href="/category?id={{a.category_id}}" class="article-category">{{ a.category }}</a>
                        </div>      

                    {% endfor %}
                {% endif %}

            </div>
        </div>
        <div class="article-wrapper">

            {% for a in articles %}

                {% if not a.is_main_in_homepage %}

                    <div class="article">
                        <div class="article__content">
                            <a href="/article?id={{a.id}}" class="article__title">{{ a.article_title }}</a>
                            <a href="/article?id={{a.id}}"><p class="article__desc">{{ a.article_description }}</p></a>
                            <a href="/profile?id={{a.author.id}}" class="article__author-name">{{ a.author }}</a>
                            <a href="/category?id={{a.category_id}}" class="article-category">{{ a.category }}</a>
                            <p class="article__date">{{ a.pub_date }}</p>
                            <button class="like-btn">
                                <svg height="24" version="1.1" width="24">
                                    <g transform="translate(0 -1028.4)">
                                        <path d="m7 1031.4c-1.5355 0-3.0784 0.5-4.25 1.7-2.3431 2.4-2.2788 6.1 0 8.5l9.25 9.8 9.25-9.8c2.279-2.4 2.343-6.1 0-8.5-2.343-2.3-6.157-2.3-8.5 0l-0.75 0.8-0.75-0.8c-1.172-1.2-2.7145-1.7-4.25-1.7z" fill="#c0392b"/>
                                    </g>
                                </svg>
                                <span>{{ a.likes }}</span>
                            </button>
                        </div>
                        <a href="/article?id={{a.id}}"><img src="{{ a.article_image.url }}" alt="Article image" class="article__img"></a>
                    </div>

                {% endif %}

            {% endfor %}
            <button class="load-btn">
                Загрузить ещё
                <svg width="21" height="21" viewBox="0 0 21 21">
                    <path d="M4 7.33L10.03 14l.5.55.5-.55 5.96-6.6-.98-.9-5.98 6.6h1L4.98 6.45z" fill-rule="evenodd"></path>
                </svg>
            </button>
        </div>
    </div>
    <footer>
        <p class="footer__info">© 2020 Yurkin Ivan | Dev version</p>
    </footer>
    {% load static %}
    <script src="{% static '/home.js' %}"></script>
    <script src="{% static '/filterSlider.js' %}"></script>
{% endblock content %}

blog/templates/pages/login.html
{% extends 'auth.html' %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/form.css' %}">
{% endblock %}

{% block title %}Вход{% endblock %}

{% block content %}
    <div class="form-container">
        <h1 class="title">Вход</h1>
        <form action="" method="POST" class="register-form">

            {% csrf_token %}

            {% for m in messages %}
                 <p class='error-message'>{{ m}}</p>
            {% endfor %}
    
            <label class="register-form__lbl" for="id_email">Имя пользователя</label>
            <input type="username" name="username" id="id_email">
            <label class="register-form__lbl" for="id_password">Пароль</label>
            <input type="password" name="password" id="id_password">

            <button type="submit" class="register-btn">Войти</button>

            <p>
                <span>Нет аккаунта?</span>
                <a class="sign-in" href="{% url 'main_app:register' %}">Зарегистрироваться</a>
            </p>

        </form>
    </div>
{% endblock %}

blog/templates/pages/register.html
{% extends 'auth.html' %}

{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/form.css' %}">
{% endblock %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <div class="form-container">
        <h1 class="title">Регистрация</h1>
        <form action="" method="POST" class="register-form">

            {% csrf_token %}

            {% if form.username.errors %}
                <p class='error-message'>{{ form.username.errors.as_text }}</p>
            {% endif %}
            {% if form.password1.errors or form.password2.errors  %}
                <p class='error-message'>{{ form.password2.errors.as_text }}</p>
            {% endif %}

            <label class="register-form__lbl" for="id_username">Имя пользователя</label>
            {{form.username}}
            <label class="register-form__lbl" for="id_password1">Пароль</label>
            {{form.password1}}
            <label class="register-form__lbl" for="id_password2">Повторите пароль</label>
            {{form.password2}}
            
            <button type="submit" class="register-btn">Зарегистрироваться</button>

            <p>
                <span>Уже есть аккаунт?</span>
                <a class="sign-in" href="{% url 'main_app:login' %}">Войти</a>
            </p>

        </form>
    </div>
{% endblock %}